spring:
  profiles:
    active: @profile.active@


#mybatis&&通用Mapper
mybatis:
  type-aliases-package: com.karle.bean
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.karle.tk.TkMapper
  identity: MYSQL


#分页插件
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: com.github.pagehelper.dialect.helper.MySqlDialect
  params: pageNum=pageNumKey;pageSize=pageSizeKey;
